/* automatically generated by rust-bindgen 0.58.1 */

pub type int_least64_t = i64;
pub type uint_least64_t = u64;
pub type int_fast64_t = i64;
pub type uint_fast64_t = u64;
pub type int_least32_t = i32;
pub type uint_least32_t = u32;
pub type int_fast32_t = i32;
pub type uint_fast32_t = u32;
pub type int_least16_t = i16;
pub type uint_least16_t = u16;
pub type int_fast16_t = i16;
pub type uint_fast16_t = u16;
pub type int_least8_t = i8;
pub type uint_least8_t = u8;
pub type int_fast8_t = i8;
pub type uint_fast8_t = u8;
extern "C" {
    pub fn fillScreen(color: u16);
}
extern "C" {
    pub fn serialPrintln(text: *const cstr_core::c_char);
}
extern "C" {
    pub fn drawLine(xs: i32, ys: i32, xe: i32, ye: i32, color: u32);
}
extern "C" {
    pub fn getTouch(x: *mut i16, y: *mut i16) -> u8;
}