#!/bin/bash
bindings=$(bindgen --use-core '../MainFirmware/LightwatchCDriver.h')
echo -n "$bindings" \
    `# Replace std::os with cstr_core` \
    | sed 's/::std::os::raw::c_char/cstr_core::c_char/g' \
    `# Remove references to std` \
    | sed '/::std/d' \
    > src/c_bindings.rs