#!/bin/bash
CMD=$1
if [ "$CMD" == "build-rust-blob" ]; then
    cd /src/rust_firmware && cargo xbuild --features="xtensa-lx-rt/lx6,xtensa-lx/lx6,esp32-hal"
    cp target/xtensa-esp32-none-elf/debug/liblightwatch_firmware.a ../rust_blob_library/src/esp32
fi
if [ "$CMD" == "build-arduino" ]; then
    ls /etc/arduino/libraries/rust_blob_library
    arduino-cli compile --fqbn esp32:esp32:twatch /src/MainFirmware
fi
if [ "$CMD" == "upload" ]; then
    if [ -v $2 ]; then
        echo "Error: Need path to device as parameter (lw upload <path>). See list below."
        arduino-cli board list
        exit 0
    fi
    arduino-cli compile --fqbn esp32:esp32:twatch /src/MainFirmware
    arduino-cli upload -p $2 --fqbn esp32:esp32:twatch /src/MainFirmware
fi
