#!/bin/bash
CMD=$1
if [ "$CMD" == "build-rust-blob" ]; then
    if [ ! -d "$BUILD_DIR/build" ]; then
        echo "Unpacking prebuilt Xtensa Rust compiler..."
        mkdir -p $BUILD_DIR && cd $BUILD_DIR && tar -xf $XTENSA_RUSTC_ARCHIVE_PATH    
    fi
    cd /src/rust_firmware && cargo xbuild --features="xtensa-lx-rt/lx6,xtensa-lx/lx6,esp32-hal"
    cp target/xtensa-esp32-none-elf/debug/liblightwatch_firmware.a ../rust_blob_library/src/esp32
fi
if [ "$CMD" == "make-rust-bindings" ]; then
    cd /src/rust_firmware && ./make_bindings
fi
if [ "$CMD" == "build-arduino" ]; then
    arduino-cli compile --fqbn esp32:esp32:twatch --build-cache-path /tmp/arduino/cache --build-path /tmp/arduino/build /src/MainFirmware
fi
if [ "$CMD" == "serial-monitor" ]; then
    if [ -v $2 ]; then
        echo "Error: Need path to device as parameter (lw upload <path>). See list below."
        arduino-cli board list
        exit 0
    fi
    minicom -D $2 -b 115200
fi
if [ "$CMD" == "upload" ]; then
    if [ -v $2 ]; then
        echo "Error: Need path to device as parameter (lw upload <path>). See list below."
        arduino-cli board list
        exit 0
    fi
    lw build-arduino
    arduino-cli upload -p $2 --fqbn esp32:esp32:twatch --input-dir /tmp/arduino/build /src/MainFirmware
fi
